### ISSUE TITLE
Intel IGD Passthrough error

### ISSUE THREAD

**Issue by Bladestar2105** [fabianishere/pve-edge-kernel#9]
In Proxmox since the last kernel updates passthrough of Intel integrated graphics devices fail.
I googled and found that implementing some patches in Kernel 5.8+ would fix the issues.
Can you review and implement them please?
https://github.com/jam3st/vfio-hd4600

**Comment by fabianishere** [comment]
Hi,

Thanks for the report! Are you aware of any effort to mainstream these patches into the Linux Stable v5.8.x tree? Moreover, can I treat this patch as a simple bug fix or is it functionality that shouldn't be included by default?

**Comment by Bladestar2105** [comment]
Hello,
I think this is a simple Bugfix. Found this when I googled for the problem.

**Comment by fabianishere** [comment]
The only reference I can find for this patch is [this](https://www.reddit.com/r/VFIO/comments/ib2idf/passthrough_of_igp/). Moreover, it seems that this patch requires specific user configuration (see [this patch](https://github.com/jam3st/vfio-hd4600/blob/master/kernel/vfio_iommu_type1.c.patch)) in order to successfully compile. Thus, these patches seem very specific as opposed to general bug fixes.

Therefore, I won't include them in my builds for now. Instead, I recommend building a kernel with these patches yourself first. If you have more information, let me know. :)
